// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skill_Assessment_Portal_Backend.Data;

#nullable disable

namespace Skill_Assessment_Portal_Backend.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Skill_Assessment_Portal_Backend.Models.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("InstructionsFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AssessmentId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("Skill_Assessment_Portal_Backend.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<int>("MaxMarks")
                        .HasColumnType("int");

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("QuestionId");

                    b.HasIndex("AssessmentId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Skill_Assessment_Portal_Backend.Models.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Passed")
                        .HasColumnType("bit");

                    b.Property<float>("Percentage")
                        .HasColumnType("real");

                    b.Property<int>("TotalMarksObtained")
                        .HasColumnType("int");

                    b.Property<int>("UserAssessmentId")
                        .HasColumnType("int");

                    b.HasKey("ResultId");

                    b.HasIndex("UserAssessmentId")
                        .IsUnique();

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Skill_Assessment_Portal_Backend.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Candidate"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Evaluator"
                        });
                });

            modelBuilder.Entity("Skill_Assessment_Portal_Backend.Models.Submission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<string>("AnswerFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int?>("MarksObtained")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAssessmentId")
                        .HasColumnType("int");

                    b.HasKey("SubmissionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserAssessmentId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Skill_Assessment_Portal_Backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentRole")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HighestQualification")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEmployed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 11, 14, 11, 44, 9, 473, DateTimeKind.Utc).AddTicks(6073),
                            CurrentRole = "Administrator",
                            Email = "admin@skillportal.com",
                            FullName = "Default Admin",
                            Gender = "Male",
                            HighestQualification = "Master's Degree",
                            IsEmployed = true,
                            PasswordHash = new byte[] { 236, 24, 80, 240, 217, 125, 126, 16, 232, 30, 64, 126, 51, 121, 108, 63, 17, 233, 201, 53, 97, 119, 233, 6, 132, 241, 44, 127, 32, 0, 60, 41, 7, 80, 206, 57, 75, 151, 20, 8, 119, 247, 221, 143, 19, 249, 106, 18, 174, 220, 112, 90, 8, 128, 85, 92, 166, 16, 94, 14, 183, 173, 240, 87 },
                            PasswordSalt = new byte[] { 165, 107, 110, 131, 177, 54, 20, 84, 150, 225, 197, 84, 158, 89, 179, 10, 95, 158, 229, 131, 4, 160, 112, 6, 75, 91, 163, 51, 162, 70, 117, 174, 240, 12, 74, 228, 250, 105, 0, 251, 166, 62, 116, 89, 237, 58, 138, 7, 134, 78, 199, 213, 215, 10, 224, 177, 13, 15, 58, 168, 245, 123, 112, 193, 193, 50, 16, 60, 113, 121, 198, 235, 39, 24, 59, 21, 30, 125, 152, 220, 237, 210, 113, 171, 125, 238, 39, 76, 227, 167, 225, 43, 45, 133, 122, 9, 190, 79, 108, 2, 181, 140, 94, 196, 116, 26, 65, 113, 77, 253, 170, 68, 62, 70, 228, 25, 84, 94, 142, 36, 142, 223, 34, 69, 82, 128, 254, 77 },
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 14, 11, 44, 9, 473, DateTimeKind.Utc).AddTicks(6167)
                        });
                });

            modelBuilder.Entity("Skill_Assessment_Portal_Backend.Models.UserAssessment", b =>
                {
                    b.Property<int>("UserAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAssessmentId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserAssessmentId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("UserId", "AssessmentId")
                        .IsUnique();

                    b.ToTable("UserAssessments");
                });

            modelBuilder.Entity("Skill_Assessment_Portal_Backend.Models.Assessment", b =>
                {
                    b.HasOne("Skill_Assessment_Portal_Backend.Models.User", "Creator")
                        .WithMany("CreatedAssessments")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Skill_Assessment_Portal_Backend.Models.Question", b =>
                {
                    b.HasOne("Skill_Assessment_Portal_Backend.Models.Assessment", "Assessment")
                        .WithMany("Questions")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("Skill_Assessment_Portal_Backend.Models.Result", b =>
                {
                    b.HasOne("Skill_Assessment_Portal_Backend.Models.UserAssessment", "UserAssessment")
                        .WithOne("Result")
                        .HasForeignKey("Skill_Assessment_Portal_Backend.Models.Result", "UserAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAssessment");
                });

            modelBuilder.Entity("Skill_Assessment_Portal_Backend.Models.Submission", b =>
                {
                    b.HasOne("Skill_Assessment_Portal_Backend.Models.Question", "Question")
                        .WithMany("Submissions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Skill_Assessment_Portal_Backend.Models.UserAssessment", "UserAssessment")
                        .WithMany("Submissions")
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("UserAssessment");
                });

            modelBuilder.Entity("Skill_Assessment_Portal_Backend.Models.User", b =>
                {
                    b.HasOne("Skill_Assessment_Portal_Backend.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Skill_Assessment_Portal_Backend.Models.UserAssessment", b =>
                {
                    b.HasOne("Skill_Assessment_Portal_Backend.Models.Assessment", "Assessment")
                        .WithMany("UserAssessments")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skill_Assessment_Portal_Backend.Models.User", "User")
                        .WithMany("UserAssessments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skill_Assessment_Portal_Backend.Models.Assessment", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("UserAssessments");
                });

            modelBuilder.Entity("Skill_Assessment_Portal_Backend.Models.Question", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Skill_Assessment_Portal_Backend.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Skill_Assessment_Portal_Backend.Models.User", b =>
                {
                    b.Navigation("CreatedAssessments");

                    b.Navigation("UserAssessments");
                });

            modelBuilder.Entity("Skill_Assessment_Portal_Backend.Models.UserAssessment", b =>
                {
                    b.Navigation("Result");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
